FROM ubuntu:latest
# apt update and install global requirements
RUN apt-get update && apt-get install -y \
    python3-pip

# apt clean and remove cached source lists
RUN apt-get clean && \
     rm -rf /var/lib/apt/lists/*

RUN pip install -U vireoSNP

ENV PATH ~/.local/bin:$PATH



